title: Birmingham River Champions
description: Birmingham River Champions (BRC) is a citizen science project led by
  the University of Birmingham, partnered by the Environment Agency, Birmingham and
  Black Country Wildlife Trust and Severn Trent's river ranger team. We are connecting
  with volunteer groups delivering fantastic conservation work across the West Midlands.
  BRC allows volunteers to monitor our vulnerable rivers by providing training and
  equipment.
url: https://birminghamriverchampions.shinyapps.io
image: https://birminghamriverchampions.shinyapps.io/favicon.ico
site_name: Birmingham River Champions
locale: en_UK
