title: Rugby River Champions
description: Rugby River Champions (BRC) is a citizen science project led by
  the University of Rugby, partnered by the Environment Agency, Rugby and
  Black Country Wildlife Trust and Severn Trent's river ranger team. We are connecting
  with volunteer groups delivering fantastic conservation work across the West Midlands.
  BRC allows volunteers to monitor our vulnerable rivers by providing training and
  equipment.
url: https://rugbyriverchampions.shinyapps.io
image: https://rugbyriverchampions.shinyapps.io/favicon.ico
site_name: Rugby River Champions
locale: en_UK
