#' 02_data_input UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd
#'
#' @importFrom shiny NS tagList
mod_02_data_input_ui <- function(id) {
  ns <- NS(id)
  tagList(
    sidebarLayout(
      sidebarPanel(
        # keep a simple selector for which form to show; detailed inputs are generated by the form module
        div(data_type_input_ui(
          ns("data_type"),
          which_data_types = c(1, 2, 3, 5),
          question_string = "What type of data did you collect? If multiple, click the top option"
        ))
      ),
      mainPanel(
        shinyjs::useShinyjs(),
        shinyjs::inlineCSS(appCSS),
        # embed the auto-generated form for the chosen table
        mod_data_entry_form_ui(
          ns("data_entry")
        )
      )
    )
  )
}

#' 02_data_input Server Functions
#'
#' @noRd
mod_02_data_input_server <- function(id) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns

    # Map the human-friendly data_type selection to a table name used by the form module
    table_name <- data_type_input_server("data_type")

    # mount the data entry form module for the chosen table
    form <- mod_data_entry_form_server("data_entry", table_name = table_name)

    # when the form is submitted, get the values and show a brief notification
    observeEvent(form$submit(), {
      vals <- form$values
      if (is.null(vals)) {
        shiny::showNotification("No values to submit.", type = "warning")
        return()
      }
      # simple feedback - show how many fields submitted
      n <- length(vals)

      # for now we just print the values (could be saved to DB in a follow-up)
      message("Form values for table '", table_name(), "':")
      tryCatch(
        {
          print(vals)
        },
        error = function(e) {
          message("(could not print values)")
        }
      )
    })
  })
}

## To be copied in the UI
# mod_02_data_input_ui("02_data_input_1")

## To be copied in the server
# mod_02_data_input_server("02_data_input_1")
