name: Deploy to shinyapps.io

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev cmake gdal-bin libabsl-dev libfontconfig1-dev libfreetype6-dev libgit2-dev pandoc

      - uses: r-lib/actions/setup-r@v2

      - name: Install terra
        run: |
          Rscript -e 'install.packages("terra", repos="https://cloud.r-project.org")'

      - name: Install renv
        run: install.packages("renv")
        shell: Rscript {0}

      - name: Restore renv packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: renv::restore(prompt = FALSE)
        shell: Rscript {0}

      - name: Check secrets exist
        run: |
          echo "Name length: ${#SHINYAPPS_NAME}"
          echo "Token length: ${#SHINYAPPS_TOKEN}"
          echo "Secret length: ${#SHINYAPPS_SECRET}"
          echo "ID length: ${#SHINYAPPS_APP_ID}"
          echo "URL length: ${#DEPLOY_URL}"
          echo "GOOGLE_CREDENTIALS_JSON length: ${#GOOGLE_CREDENTIALS_JSON}"
        env:
          SHINYAPPS_NAME: ${{ github.ref == 'refs/heads/main' && secrets.MAIN_SHINYAPPS_NAME || secrets.DEV_SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.MAIN_SHINYAPPS_TOKEN || secrets.DEV_SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ github.ref == 'refs/heads/main' && secrets.MAIN_SHINYAPPS_SECRET || secrets.DEV_SHINYAPPS_SECRET }}
          SHINYAPPS_APP_ID: ${{ github.ref == 'refs/heads/main' && secrets.MAIN_SHINYAPPS_APP_ID || secrets.DEV_SHINYAPPS_APP_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          DEPLOY_URL: ${{ github.ref == 'refs/heads/main' && secrets.MAIN_URL || secrets.DEV_URL }}

      - name: Install rsconnect requirements
        run: install.packages(c("rsconnect", "desc"))
        shell: Rscript {0}

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ github.ref == 'refs/heads/main' && secrets.MAIN_SHINYAPPS_NAME || secrets.DEV_SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.MAIN_SHINYAPPS_TOKEN || secrets.DEV_SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ github.ref == 'refs/heads/main' && secrets.MAIN_SHINYAPPS_SECRET || secrets.DEV_SHINYAPPS_SECRET }}
          SHINYAPPS_APP_ID: ${{ github.ref == 'refs/heads/main' && secrets.MAIN_SHINYAPPS_APP_ID || secrets.DEV_SHINYAPPS_APP_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          DEPLOY_URL: ${{ github.ref == 'refs/heads/main' && secrets.MAIN_URL || secrets.DEV_URL }}
        run: |
          rsconnect::setAccountInfo(
            name = Sys.getenv("SHINYAPPS_NAME"),
            token = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )

          writeLines(
            Sys.getenv("DEPLOY_URL"),
            "inst/extdata/google_url.txt"
          )

          writeLines(
            Sys.getenv("GOOGLE_CREDENTIALS_JSON"),
            "inst/extdata/birminghamriverchampions-db5399f61d80.json"
          )

          app_id <- Sys.getenv("SHINYAPPS_APP_ID")
          app_id <- if (nzchar(app_id)) app_id else NULL

          rsconnect::deployApp(
            appName = desc::desc_get_field("Package"),
            appTitle = desc::desc_get_field("Package"),
            appFiles = c(
              "R/",
              "inst/",
              "NAMESPACE",
              "DESCRIPTION",
              "app.R"
            ),
            appId = app_id,
            lint = FALSE,
            forceUpdate = TRUE
          )
        shell: Rscript {0}